# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: irenejoy21testapp
# "service" is the name of this project. This will also be added to your AWS resource names.
service: bannerService

provider:
  name: aws
  runtime: nodejs24.x
  region: us-east-1
  environment:
    BUCKET_NAME: banner-images-ads-irenejoy21-dev-12-new 
    DYNAMODB_TABLE: Banners
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
      Resource: 
        - arn:aws:s3:::banner-images-ads-irenejoy21-dev-12-new/*
    - Effect: 'Allow'
      Action:
        - dynamodb:PutItem
      Resource: 
        - arn:aws:dynamodb:us-east-1:660880134927:table/Banners

  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

resources:
  Resources:
    BannerImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: banner-images-ads-irenejoy21-dev-12-new 
    BannersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Banners
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: fileName
            AttributeType: S #string
        KeySchema:
          - AttributeName: fileName
            KeyType: HASH #partition key

functions:
  uploadBanner:
    handler: handlers/uploadBanner.getUploadUrl
    events:
      - httpApi:
          path: /upload.banner
          method: post
  confirmUpload:
    handler: handlers/confirmUpload.confirmUpload
    events:
      - s3:
          bucket: banner-images-ads-irenejoy21-dev-12-new 
          event: s3:ObjectCreated:Put
          existing: true
